# Generated by Django 5.0.6 on 2024-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
